### ISSUE TITLE
Is there a tool to update gtf/gff file according to orfipy results?

### ISSUE THREAD

**Issue by xiekunwhy** [urmi-21/orfipy#10]
Hi,

Is there a tool to update gtf/gff(generated by stringtie2 or scallop2) file according to orfipy results? Add splice sites, UTRs, CDSs to existing gtf/gff file.

Best,
Kun

**Comment by urmi-21** [comment]
Hi Kun,
orfipy can extract all the possible ORFs on a transcript, it doesn't annotate UTRs. You can use orfipy on the spliced transcripts and then adjust your gene model. In past, I have used [mikado](https://github.com/EI-CoreBioinformatics/mikado) to predict novel genes by aggregating transcripts predicted by RNA-Seq datasets. Mikado provides a step where you can input the ORFs bed file. 

**NOTE**: if you choose to provide orfipy ORFs to mikado, ORFs must be in bed12 format. To bed12 output, run orfipy as:

```
orfipy testseq.fa --min 100 --bed12 of.bed --partial-5 --partial-3 --include-stop
```
Hope this helps.
