### ISSUE TITLE
ImportError: undefined symbol: PySlice_Adjustindices

### ISSUE THREAD

**Issue by vkulaganathan** [urmi-21/orfipy#13]
Hello @urmi-21 
Thanks for the tool. I installed it successfully.
However, it does not work.
I get the following output for the command:- `orfipy -h`

![image](https://user-images.githubusercontent.com/21201645/164155728-5089cf33-515b-47cd-86d6-b576a533af8e.png)

Can you please suggest a solution?

**Comment by urmi-21** [comment]
Hi @VJ-Ulaganathan 
could you please provide more info? How did you install orfipy via conda or pip? If you didn't use conda, is it possible for you to use conda?
