### ISSUE TITLE
OverflowError: cannot serialize a string larger than 4GiB

### ISSUE THREAD

**Issue by IgorFesenko** [urmi-21/orfipy#16]
Hello,

I have got this error "OverflowError: cannot serialize a string larger than 4GiB". How can I fix it?

Thanks,
Igor

**Comment by urmi-21** [comment]
Hi @IgorFesenko I am not sure if I have seen this before. Could you please provide an example on how to reproduce this bug?

**Comment by IgorFesenko** [comment]
Hi @urmi-21, This problem is caused by large FASTA files. I used combined bacterial genomes to predict ORFs. The problem is solved if I split the files into several pieces.

**Comment by urmi-21** [comment]
Thanks for confirming @IgorFesenko I will close this now.
