### ISSUE TITLE
Not all ORFs found?

### ISSUE THREAD

**Issue by krabapple** [urmi-21/orfipy#8]
I'm trying to understand how this tool works.  

Here is a sequence of ~1 kb length:

>region_of_interest
GACTCGGTGCTATGTTCTGAATATTTCTGACTTGCATTTTTAATGGAGATAAAATGAAGCATTTAATACATGACGTAGATGAAGACATGAATGAAACTACAGACAAACTTAACTCTTCTCTCATTCTTCCTTTCAGTAAGGACTATGAGTTCTGTTCAAATGGCGTTTATTTCTATTGTGGAAAGATGGGTTCAGGTAAGACATTTAATTTAATTCGTCATATACTCATAACAGAACGTTTAGGAAATGACTCATATTATGACCAAATCATTATATCAGCAACTTCAGACTCTATGGACTCAACAGCGAAAACATTTATGTCAAAAGTTCAAGCCTCTGTCGTTAAAGTTCCAGACAGTGAACTCATTGAATTTCTTCAACGTTACATTCGACGTAAGAGGAAATATTATGCCATCGTTGAATTTATACAGTCAGGAATGCAAAAGACTTCTGAGGAGATGGAAAGAATTATTGACAAACACCACTTACGTCAGTACTCAGGAGTTTACGATATGAAACGACTGACAAACTACATTCTATCAAAACTTTCAAAATACCCCTTCAAAAAATATCCTTCAAACACTCTGCTCGTTTGCGACGACTTCGCTGGTAAAGGTTTAGTGTCAAAACCAGACTCACCATTAGCTAATATCATTACTAAAGTCAGACATTACCACTTAACTGTAGCAATACTTATGCAAACATGGAGGTTTTTAGCTTTAAACATAAAACGTCTCATAACTGACTTCGTTATCTTTCAAGGTTTCTCACGTTATGATATTGAACTCATTTGGAAACAGTCAGGTATAACATTACCTTTTGAAGAAATTTGGGAAGCATATAAGTCTCTCATCTCTCCTCGTTCATACCTTGAGATTCATATCATGACTAATACCATTAAAGTCAAAAATATTCCATGGGAACGACCAACATTGTTTTAAAGTTTAACCTTCAATTGACTGA

In the IGV genome viewer, where ATG = green bar and stop codon = red, the forward sequence appears thus with 3-frame translation:

![igv_snapshot](https://user-images.githubusercontent.com/49412726/131732884-46a87488-de64-4f73-83e4-ab2701a6a7c6.png)

I note 10 start sites in frame 3, following the first STOP. Each of these, I thought, would constitute an alternate ORF, all ending in the same downstream STOP 

But the output of orfipy is :
//
$ orfipy new_seq.fa --min 100 --max 100000 --procs 4 | sort -k2,2n
orfipy version 0.0.4
Using translation table: Standard (transl_table=1) start: ['TTG', 'CTG', 'ATG'] stop: ['TAA', 'TAG', 'TGA']
Setting chunk size 12053 MB. Procs 4
Logs will be saved to: orfipy_new_seq.fa_out/orfipy_2021_09_01_15_35_34.526156.log
Processed 1 sequences in 0.02 seconds

region_of_interest      26      938     ID=region_of_interest_ORF.3;ORF_type=complete;ORF_len=912;ORF_frame=3;Start:CTG;Stop:TAA        0       +
region_of_interest      90      210     ID=region_of_interest_ORF.1;ORF_type=complete;ORF_len=120;ORF_frame=1;Start:ATG;Stop:TAA        0       +
region_of_interest      246     513     ID=region_of_interest_ORF.2;ORF_type=complete;ORF_len=267;ORF_frame=1;Start:ATG;Stop:TGA        0       +
region_of_interest      323     431     ID=region_of_interest_ORF.4;ORF_type=complete;ORF_len=108;ORF_frame=-2;Start:CTG;Stop:TGA       0       -
region_of_interest      532     667     ID=region_of_interest_ORF.5;ORF_type=complete;ORF_len=135;ORF_frame=-3;Start:CTG;Stop:TAG       0       -
//
Can you explain why orfipy excluded so many potential ORFs here?  And is there an option to force it to report them?

**Comment by urmi-21** [comment]
Hi, thanks for trying out orfipy. The use cases that orfipy covers are defined in our [paper](https://doi.org/10.1093/bioinformatics/btab090). Currently orfipy doesn't report the case you mentioned. e.g. consider the following:
ATG TTT GGG ATG GGG CCC TAG

In this case, orfipy will report the longest possible ORF starting from the first ATG (5' end), the second ATG is considered as an internal codon. From what I understood is that you would like to have two orfs reported as:
ATG TTT GGG ATG GGG CCC TAG and ATG GGG CCC TAG

This is doable in orfipy and I can consider adding a feature. I am first interested to know if such a case is biologically useful. Could you please some papers on this where the 5' start site is ignored for a shorter 3' one.

Meanwhile, what you can do is write a small script to cover your use case. After you have sequence output from orfipy, you could write a script to see how many of the ORFs have internal start codons and extract those as separate ORFs.

Here is a quick example using orfipy (please test and validate the correctness and improve as per your requirements)
1. First extract all ORFs using --dna option `orfipy --min 0  --dna d.fa seq.fa`
2. Use orfipy to extract internal ORFs for each ORF found in step 1:

```
import orfipy_core
seq='ATGTTTGGGATGGGGCCC' #this is output from running orfipy
while seq:
    seq=seq[3:]
    for start,stop,strand,description in orfipy_core.orfs(seq,minlen=3,maxlen=1000,partial3=True,starts=['ATG'],stops=['TAG']):
        print('>alt_orf',start,stop)
        print(seq[start:])
        seq=seq[start:]
```

**Comment by krabapple** [comment]
Primarily I am basing it on RNA-seq evidence for the genome I'm interested
in (RNAseq reads mapped to predicted genes).  I see many instances where
RNA seq coverage begins at the second Met , with no coverage of the regions
between the first and 2nd Met.


On Mon, Sep 6, 2021 at 4:12 PM Urminder Singh ***@***.***>
wrote:

> Hi, thanks for trying out orfipy. The use cases that orfipy covers are
> defined in our paper
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__doi.org_10.1093_bioinformatics_btab090&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=2Zel7OrFNp7vge-EaCVcNA&m=rNNYKdNQ_f9bwEO9-mMlbLcxTf_ETKMlYUehGkyVocU&s=VlP2f_jWQYJUqt1xXbpSu17T-xgehIIxRirG7uKvAMc&e=>.
> Currently orfipy doesn't report the case you mentioned. e.g. consider the
> following:
> ATG TTT GGG ATG GGG CCC TAG
>
> In this case, orfipy will report the longest possible ORF starting from
> the first ATG (5' end), the second ATG is considered as an internal codon.
> From what I understood is that you would like to have two orfs reported as:
> ATG TTT GGG ATG GGG CCC TAG and ATG GGG CCC TAG
>
> This is doable in orfipy and I can consider adding a feature. I am first
> interested to know if such a case is biologically useful. Could you please
> some papers on this where the 5' start site is ignored for a shorter 3' one.
>
> Meanwhile, what you can do is write a small script to cover your use case.
> After you have sequence output from orfipy, you could write a script to see
> how many of the ORFs have internal start codons and extract those as
> separate ORFs.
>
> Here is a quick example using orfipy (please test and validate the
> correctness and improve as per your requirements)
>
>    1. First extract all ORFs using --dna option orfipy --min 0 --dna d.fa
>    seq.fa
>    2. Use orfipy to extract internal ORFs for each ORF found in step 1:
>
> import orfipy_core
> seq='ATGTTTGGGATGGGGCCC' #this is output from running orfipy
> while seq:
>     seq=seq[3:]
>     for start,stop,strand,description in orfipy_core.orfs(seq,minlen=3,maxlen=1000,partial3=True,starts=['ATG'],stops=['TAG']):
>         print('>alt_orf',start,stop)
>         print(seq[start:])
>         seq=seq[start:]
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_urmi-2D21_orfipy_issues_8-23issuecomment-2D913837244&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=2Zel7OrFNp7vge-EaCVcNA&m=rNNYKdNQ_f9bwEO9-mMlbLcxTf_ETKMlYUehGkyVocU&s=icAqfllpwWONgs2--RGyWqvlPfcG53frWpgeSSQOYGE&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ALY7U5TDBA7HRZYE6YGJIVTUAUODRANCNFSM5DHHCMCQ&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=2Zel7OrFNp7vge-EaCVcNA&m=rNNYKdNQ_f9bwEO9-mMlbLcxTf_ETKMlYUehGkyVocU&s=uhq3pAGQ-5nPGfU-EzP2Ga2Y6vB5mb3FMRmiivhJQUY&e=>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=2Zel7OrFNp7vge-EaCVcNA&m=rNNYKdNQ_f9bwEO9-mMlbLcxTf_ETKMlYUehGkyVocU&s=qRRKsjBTUdsWxIuQkCzm8XBEyOJ78VV5Pm0ysPz-sck&e=>
> or Android
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=2Zel7OrFNp7vge-EaCVcNA&m=rNNYKdNQ_f9bwEO9-mMlbLcxTf_ETKMlYUehGkyVocU&s=w0n60TeCKA67I2UQzSUoJzVTfh2y9z6MRtFRKE02PBc&e=>.
>
>


-- 
Dr. Steven Sullivan
Center for Genomics & Systems Biology
New York University
12 Waverly Place
New York, NY 10003

**Comment by urmi-21** [comment]
Thanks for the explanation. I hope my suggestion above helped. I am closing this issue for now. I may consider covering the usecase you suggested in future releases. Feel free to reopen if you have more comments.
