### ISSUE TITLE
Full length ORF 

### ISSUE THREAD

**Issue by apoosakkannu** [urmi-21/orfipy#9]
Hi, I am using the orfipy. It sounds great tool for my recent work. I wonder could it be possible only to get full length orf not the partial orfs? Please let me know if there is any possibility?

**Comment by urmi-21** [comment]
Hi @apoosakkannu! Glad to know orfipy could be helpful for your research. However, I am not sure if I understand your question. What do you mean by full-length ORFs? By default, orfipy will report only complete orfs within the specified length thresholds. If you want the longest ORF you can run with the parameter `--longest` . Partials ORFs are not reported till you provide `--partial-3` and `--partial-5` options. Let me know if this answers your question.
